### ISSUE TITLE
Focus move up one line after press enter key

### ISSUE THREAD

**Issue by newset** [jhollingworth/bootstrap-wysihtml5#344]
I have this bug, when press enter key once, then press it again, the cursor will first move down, then move up to the line before. and this is only affecting Chrome, anybody help?

**Comment by Waxolunist** [comment]
As mentioned here: https://github.com/xing/wysihtml5/issues/497

This repo is not maintained. I suggest switching over to https://github.com/Waxolunist/bootstrap3-wysihtml5-bower

**Comment by mumenmusa** [comment]
@Waxolunist Unfortunately, we are still running on Bootstrap 2 and in the process of transitioning to Bootstrap 3 but not quite ready yet. I would like to fork hollingworth's repo and fix this issue for now. Can you point me to the fix to this issue? I would greatly appreciated.

**Comment by Waxolunist** [comment]
Sorry, I can't. Because this was fixed in the fork by edicy/wysihtml5. 
You are using a not maintained component based on a not maintained editor.
The changes from bs2 to bs3 haven't been big, just some classes have changed.
What you could do is to fork my repo and change the templates. Shouldn't be a big deal.
Maybe you can add an option for bs2, which adds the correct classes instead of the bs3 classes.
